LANG=en_GB.UTF-8
LC_ADDRESS=da_DK.UTF-8
LC_IDENTIFICATION=da_DK.UTF-8
LC_MEASUREMENT=da_DK.UTF-8
LC_MONETARY=da_DK.UTF-8
LC_NAME=da_DK.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_PAPER=da_DK.UTF-8
LC_TELEPHONE=da_DK.UTF-8
LC_TIME=en_GB.UTF-8

