-- Generated by nwg-displays on 2026-07-20 at 22:29:16. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "2816x144",
    scale = 1.5
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1280x0",
    scale = 1.25
})
