# activity names (first activity is treated as default)
# note: only a-z A-Z 0-9 - _ characters are allowed in the name
activities = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

# number of workspaces in x and y dimensions
workspaces = [1, 10]

# specify some named foci to load by default
# named_focii = { "1" = "my-activity:(1 1)", "2" = "my-activity:(2 2)" }

# specify icon theme for `hyprkool info` commands
icon_theme = "Papirus"

# specify the default value of --window-icon-try-min-size for `hyprkool info` commands
window_icon_try_min_size = 32

[daemon]
# remember last focused workspace in an activity
remember_activity_focus = true

# execute fallback commands if daemon cannot be reached
fallback_commands = true

[daemon.mouse]
switch_workspace_on_edge = false

# how often to poll for cursor position
# polling_rate = 300 # in ms

# number of pixels to consider as edge
# edge_width = 0

# number of pixels to push cursor inside when it loops around
# edge_margin = 2