# ==== source ====
#   https://github.com/MrVivekRajan/Hyprlock-Styles/blob/main/Style-4/hyprlock.conf
# BACKGROUND
background {
    monitor =
    path = ~/.config/assets/lockpapers/LightMode.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# NAME
label {
    monitor =
    text = Zarstenator
    color = rgba(3B4252FF)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 20
    font_family = JetBrainsMono NF Bold
    position = 0, 110
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"$TIME")</span>"
    color = rgba(D08770FF)
    font_size = 60
    font_family = JetBrainsMono NF Bold
    position = 0, -8
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = rgba(4C566AFF)
    font_size = 19
    font_family = JetBrainsMono NF Bold
    position = 0, -60
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(3B4252FF)
    rounding = -1
    border_size = 0
    border_color = rgba(ECEFF4FF)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, -210
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgba(D8DEE9FF)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono NF
    position = 0, -210
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.4 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(2E3440FF)
    inner_color = rgba(2E3440FF)
    font_color = rgba(D8DEE9AA)
    fade_on_empty = false
    font_family = JetBrainsMono NF Bold
    placeholder_text = <i><span foreground="##D8DEE9AA">🔒  Enter Password</span></i>
    hide_input = false
    position = 0, -288
    halign = center
    valign = center
}
