-- Generated by nwg-displays on 2026-08-14 at 00:10:10. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@59.95",
    position = "0x0",
    scale = 1.25
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "2048x0",
    scale = 1.0
})
