-- Generated by nwg-displays on 2026-09-04 at 15:12:59. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "0x0",
    scale = 1.25,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1280x800@59.81",
    position = "1536x0",
    scale = 1.0,
    vrr = 0
})
